language: python
python:
  - "3.6"
services:
  - docker
install:
  - docker-compose -f test.yml up -d 
  - sleep 60
script:
  - docker ps -a 
  - docker-compose -f test.yml run -e DATABASE_URL django pytest
